### PR TITLE
Inline menu prop

### PR DESCRIPTION
**Pull request by shrunyan**
Based on suggestions from [pull/13](https://github.com/hubgit/react-prosemirror/pull/13) I've refactored to allow the [`MenuBar` to accept a `floating` Boolean prop](https://github.com/hubgit/react-prosemirror/compare/master...zesty-io:inline-menu-prop?expand=1#diff-c4b49d0ede47680d57ef4d4de2fd1269R38) which will tell it to handle determining menu position.

I was unable to abstract away the need for [providing the `view` prop](https://github.com/hubgit/react-prosemirror/compare/master...zesty-io:inline-menu-prop?expand=1#diff-6e996d5d0ced8b185ef417268b34093bR45) which is a reference to the underlying Prosemirror editor. Because of how the `Editor` component is handed to the render prop I can't determine away to get a reference to the `view`. Tried a larger refactor but was unable to achieve the desired result without losing the ability to control your menu through the `render` prop. Which is not an acceptable trade-off in my point of view, since that is arguably the most important feature of these components structure.

Handled a few of the floating menu placement edge cases. I'm sure this logic and styling could be improved.

_It should be noted the [setup is a little cumbersome with requiring both the `view` and `floating` prop](https://github.com/hubgit/react-prosemirror/compare/master...zesty-io:inline-menu-prop?expand=1#diff-6361925565e20ac2dd088f3a2e7dad24R41) be provided in order to deliver the inline menu experience._

If accepted closes https://github.com/hubgit/react-prosemirror/pull/13

---
_Examples of menu placement._

**Typical menu placement when there are now window collisions.**
localhost_3000_ 2

**Menu determines it's to close to window right hand and switches direction.**
localhost_3000_

**Menu determines it's to close to the top and switches direction.**
localhost_3000_ 1

### CODE REVIEW

**Comment by shrunyan** [comment]
Hi @hubgit, just checking in to see if you had any thoughts on this solution.

**Comment by hubgit** [comment]
Hi @shrunyan - this seems like a good approach, but I haven't had time to give it a proper try yet.

Do you need this to be merged so you can use it soon?

**Comment by shrunyan** [comment]
Yes I'll need to ship a solution in about 2 weeks. I can always fork and merge upstream if this lands.

**Comment by hubgit** [comment]
I've merged #16 which adds a `Floater` component for displaying a floating menu bar when there's a selection in the editor. Give that a try (it needs a few changes to the props and onChange handler as well) and see if it works for you, and feel free to open an issue if you'd like to see different behaviour.

**Pull request closed without merging**
